dist: xenial
addons:
  sonarqube: true
cache:
  directories:
    - $HOME/.m2
script:
  - mvn -f "main-app" -DskipTests clean install
  - mvn -f "web-app" -DskipTests clean install
  - mvn -f "LandabusBot" -DskipTests clean install
  - mvn -f "datu-jasotzailea" -DskipTests clean install
  - sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.login=$SONAR_TOKEN -X
  - zip landabus.zip "Dockerrun.aws.json" "main-app/target/main-app.jar" "web-app/target/web-app.jar"
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  zip_file: "landabus.zip"
  access_key_id:
    secure: ${AWS_ACCESS_KEY_ID}
  secret_access_key:
    secure: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  app: "landabus"
  env: "landabus-test"
  bucket_name: "elasticbeanstalk-eu-west-1-697427844966"
