version: "2.1"
services:
  telegram-bot:
    image: maven:3.6.1-jdk-8-alpine
    command: ["mvn", "-f", "LandaBusBot","spring-boot:run"]
    working_dir: /usr/src/landabus
    volumes:
      - ${PWD}:/usr/src/landabus
      - ${HOME}/.m2:/root/.m2
    depends_on:
      - main-app
    environment:
      - TELEGRAM_TOKEN
      - TELEGRAM_USERNAME
