version: "2.1"
services:
  telegram-bot:
    image: maven:3.6.1-jdk-8-alpine
    command: ["mvn","spring-boot:run"]
    working_dir: /usr/src/landabus/LandabusBot
    volumes:
      - ${PWD}:/usr/src/landabus
      - ${HOME}/.m2:/root/.m2
    depends_on:
      main-app:
        condition: service_started
    environment:
      - COM_PROTOCOL
      - MAINAPP_HOST
      - MAINAPP_PORT
      - TELEGRAM_TOKEN
      - TELEGRAM_USERNAME
