version: "2.1"

services:
  db:
    image: mysql:8.0.16
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - 3306:3306
  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    environment:
      - RABBITMQ_NODE_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - 15672:15672
  main-app:
    image: maven:3.6.1-jdk-8-alpine
    command: ["mvn","-f", "main-app", "spring-boot:run"]
    environment:
      - MYSQL_DATABASE
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MAINAPP_PORT
    working_dir: /usr/src/landabus
    volumes:
      - ${PWD}:/usr/src/landabus
      - ${HOME}/.m2:/root/.m2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${MAINAPP_PORT}:${MAINAPP_PORT}"
  datu-jasotzailea:
    image: maven:3.6.1-jdk-8-alpine
    command: ["mvn","-f", "datu-jasotzailea","spring-boot:run"]
    environment:
      - COM_PROTOCOL
      - MAINAPP_HOST
      - MAINAPP_PORT
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
    working_dir: /usr/src/landabus
    volumes:
      - ${PWD}:/usr/src/landabus
      - ${HOME}/.m2:/root/.m2
    depends_on:
      - main-app
      - rabbitmq
  web-app:
    image: maven:3.6.1-jdk-8-alpine
    command: ["mvn", "spring-boot:run"]
    environment:
      - MAINAPP_HOST
      - MAINAPP_PORT
      - WEB_PORT
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - OIDC_REDIRECT
    working_dir: /usr/src/landabus/web-app
    volumes:
      - ${PWD}:/usr/src/landabus
      - ${HOME}/.m2:/root/.m2
    depends_on:
      - main-app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
