//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.02 at 05:49:51 PM CEST 
//


package landakoop.landabus.mainapp.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the landakoop.landabus.mainapp.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: landakoop.landabus.mainapp.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutobusGeldialdiaResponse }
     * 
     */
    public AutobusGeldialdiaResponse createAutobusGeldialdiaResponse() {
        return new AutobusGeldialdiaResponse();
    }

    /**
     * Create an instance of {@link AutobusGeldialdiaSoap }
     * 
     */
    public AutobusGeldialdiaSoap createAutobusGeldialdiaSoap() {
        return new AutobusGeldialdiaSoap();
    }

    /**
     * Create an instance of {@link AutobusGeldialdiaRequest }
     * 
     */
    public AutobusGeldialdiaRequest createAutobusGeldialdiaRequest() {
        return new AutobusGeldialdiaRequest();
    }

}
