INSERT INTO geltokia(izena) values('Amaiur');
INSERT INTO geltokia(izena) values('Bera');
INSERT INTO geltokia(izena) values('Ziga');
INSERT INTO geltokia(izena) values('Lesaka');
INSERT INTO geltokia(izena) values('Igantzi');
/*INSERT INTO geltokia(izena) values('Arantza');
INSERT INTO geltokia(izena) values('Etxalar');
INSERT INTO geltokia(izena) values('Sunbilla');
INSERT INTO geltokia(izena) values('Elgorriaga');
INSERT INTO geltokia(izena) values('Doneztebe');
*/
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(1,2,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(2,3,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(3,2,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(1,5,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(1,3,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(4,2,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(2,3,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(5,1,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(4,3,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(4,1,1,1);
/*INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(10,4,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(1,10,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(3,4,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(7,4,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(4,7,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(9,2,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(5,10,1,1);
INSERT INTO eskaera(geltokiaA,geltokiaB,irteeraOrdua,helmugaOrdua)  VALUES(8,6,1,1);*/

INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(1,2,18);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(1,3,7);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(1,4,15);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(1,5,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(2,1,18);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(2,3,16);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(2,4,4);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(2,5,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,1,7);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,2,16);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,4,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,5,14);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,1,15);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,2,4);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,3,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,5,2);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,1,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,2,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,3,14);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,4,2);
/*INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,4,17);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,5,16);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,6,9);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,7,4);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,8,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,9,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(3,10,4);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,1,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,2,1);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,3,18);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,5,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,6,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,7,12);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,8,9);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,9,15);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(4,10,15);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,1,14);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,2,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,3,9);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,4,2);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,6,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,7,7);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,8,19);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,9,19);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(5,10,17);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,1,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,2,4);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,3,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,4,7);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,5,18);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,7,17);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,8,16);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,9,14);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(6,10,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,1,8);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,2,11);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,3,8);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,4,6);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,5,11);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,6,16);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,8,3);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,9,9);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(7,10,12);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,1,17);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,2,18);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,3,19);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,4,6);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,5,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,6,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,7,11);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,9,1);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(8,10,9);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,1,3);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,2,16);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,3,18);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,4,4);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,5,4);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,6,15);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,7,15);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,8,3);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(9,10,18);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,1,5);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,2,17);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,3,0);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,4,7);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,5,1);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,6,13);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,7,1);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,8,12);
INSERT INTO distantzia(geltokiaA, geltokiaB, denbora) VALUES(10,9,4);
*/

INSERT INTO erabiltzailea(izena) VALUES ('Hodei');
INSERT INTO erabiltzailea(izena) VALUES ('Bingen');
INSERT INTO erabiltzailea(izena) VALUES ('Kepa');
INSERT INTO erabiltzailea(izena) VALUES ('Iñigo');

INSERT INTO linea(izena) VALUES ('1');
INSERT INTO linea(izena) VALUES ('2');
INSERT INTO linea(izena) VALUES ('3');
INSERT INTO linea(izena) VALUES ('4');

INSERT INTO ibilbidea(lineaID) VALUES (1);
INSERT INTO ibilbidea(lineaID) VALUES (2);
INSERT INTO ibilbidea(lineaID) VALUES (3);
INSERT INTO ibilbidea(lineaID) VALUES (4);

